service: file-upload
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handler:
    handler: handler.handler
    events:
      #- httpApi: '*'
      - http: ANY /{proxy+}
      - http: ANY /
      - s3:
          bucket: html-corrector-bucket-devy
          event: s3:ObjectCreated:*"
